image: gitlab/dind:latest

services:
- docker:dind

stages:
- test
- release
- deploy

variables:
  CONTAINER_RELEASE_IMAGE: gitlab.madisonhub.org:4567/cciccia/slack-mafia:$CI_BUILD_REF_NAME

test:
  stage: test
  script:
    - docker-compose -f docker-compose.test.yml up --build --abort-on-container-exit

release:
  stage: release
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN gitlab.madisonhub.org:4567
    - docker build -t $CONTAINER_RELEASE_IMAGE -f ./app/Dockerfile-stage ./app
    - docker push $CONTAINER_RELEASE_IMAGE
  only:
    - master