version: '2'
services:
  app:
    build: ./app
    ports:
      - "18000:3000"
    env_file:
      - env/development.env
    command: ["npm", "run", "watch"]
    volumes:
      - ./app:/src/app
      - modules:/src/app/node_modules

volumes:
  modules:
