version: '3'
services:
  app:
    build: .
    env_file:
      - env/development.env
    depends_on:
      - postgres
    command: ["npm", "run", "watch"]
    volumes:
      - .:/app
  postgres:
    image: postgres:9.6.3
    ports:
      - "15432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
    