version: '3'
services:
  app:
    build: .
    env_file:
      - env/development.env
    depends_on:
      - postgres
  postgres:
    image: postgres:9.6.3
    volumes:
      - ./data:/var/lib/postgresql/data
    