version: '3'
services:
  app:
    build: ./app
    ports:
      - "18000:3000"
    env_file:
      - env/testing.env
    depends_on:
      - postgres
    command: ["npm", "run", "test"]
    volumes:
      - ./app:/src/app
      - modules:/src/app/node_modules
  postgres:
    image: postgres:9.6.3
    volumes:
      - ./data:/var/lib/postgresql/data

volumes:
  modules:
